In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [10]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 +b

In [11]:
# cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize, Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [12]:
# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [13]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  3785.0054 
Prediction:
 [ 94.90524 120.57186 115.37128 124.35839  95.04429]
10 Cost:  3.7687461 
Prediction:
 [149.30899 185.94786 179.79422 194.51286 144.90686]
20 Cost:  3.716002 
Prediction:
 [149.48055 186.14088 179.99124 194.7269  145.05121]
30 Cost:  3.697988 
Prediction:
 [149.48799 186.13667 179.99391 194.72931 145.04517]
40 Cost:  3.6800354 
Prediction:
 [149.49493 186.13188 179.99602 194.73108 145.03867]
50 Cost:  3.6622047 
Prediction:
 [149.50186 186.12712 179.99812 194.73283 145.0322 ]
60 Cost:  3.6444778 
Prediction:
 [149.50876 186.12238 180.00018 194.73459 145.02574]
70 Cost:  3.62684 
Prediction:
 [149.51562 186.11761 180.00226 194.73634 145.0193 ]
80 Cost:  3.6092675 
Prediction:
 [149.5225  186.11288 180.00432 194.7381  145.01288]
90 Cost:  3.5918121 
Prediction:
 [149.52934 186.10817 180.0064  194.73985 145.00647]
100 Cost:  3.5744545 
Prediction:
 [149.53618 186.10347 180.00847 194.7416  145.00009]
110 Cost:  3.5571907 
Prediction:
 [149.54298 186.09879 18

In [16]:
##### ->>>>> 거의 사용하지 않는다(위)
## Matrix 로 사용!

## using Matrix

In [15]:
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [18]:
# cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [20]:
# Minimize, Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [21]:
# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [22]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  81420.38 
Prediction:
 [[ -98.566956]
 [-121.96645 ]
 [-118.57244 ]
 [-127.96331 ]
 [ -94.626236]]
10 Cost:  9.193072 
Prediction:
 [[153.82826]
 [181.41335]
 [180.34274]
 [197.54848]
 [136.78047]]
20 Cost:  8.407603 
Prediction:
 [[154.58165]
 [182.33838]
 [181.24406]
 [198.53067]
 [137.49036]]
30 Cost:  8.367586 
Prediction:
 [[154.57365]
 [182.34827]
 [181.2437 ]
 [198.53091]
 [137.5022 ]]
40 Cost:  8.327884 
Prediction:
 [[154.56342]
 [182.35536]
 [181.24063]
 [198.52824]
 [137.5119 ]]
50 Cost:  8.288376 
Prediction:
 [[154.55316]
 [182.36243]
 [181.23755]
 [198.52554]
 [137.52155]]
60 Cost:  8.249052 
Prediction:
 [[154.54295]
 [182.36946]
 [181.23447]
 [198.52284]
 [137.53119]]
70 Cost:  8.209918 
Prediction:
 [[154.53278]
 [182.3765 ]
 [181.23143]
 [198.52017]
 [137.54083]]
80 Cost:  8.171016 
Prediction:
 [[154.52261]
 [182.3835 ]
 [181.22836]
 [198.51749]
 [137.55042]]
90 Cost:  8.132358 
Prediction:
 [[154.51251]
 [182.3905 ]
 [181.22534]
 [198.51483]
 [137.55998]]
1