In [16]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

In [17]:
# Training and Test dataset
# Training dataset과 Test dataset을 나눈다!

x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

In [18]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [19]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [20]:
# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [21]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 6.112259 [[-0.6341176  -1.0953087  -2.0971997 ]
 [-1.3848805   0.31368127 -0.09990022]
 [-0.04740678  0.3945959   0.49441803]]
1 4.0912895 [[-0.60988635 -1.1480024  -2.068737  ]
 [-1.2240226   0.08252636 -0.02960323]
 [ 0.11378047  0.18062368  0.547203  ]]
2 2.9479427 [[-0.5877642  -1.154887   -2.0839746 ]
 [-1.0680087   0.07300343 -0.17609432]
 [ 0.2695871   0.19302668  0.37899333]]
3 2.2423544 [[-0.57084566 -1.1886672  -2.067113  ]
 [-0.924769   -0.0839565  -0.16237405]
 [ 0.40681386  0.06023891  0.37455437]]
4 1.7123628 [[-0.5682738  -1.1861686  -2.0721834 ]
 [-0.8256176  -0.06675207 -0.27872983]
 [ 0.48871487  0.1024535   0.25043875]]
5 1.5170124 [[-0.5801194  -1.1976312  -2.048875  ]
 [-0.7872011  -0.13864662 -0.24525174]
 [ 0.5040839   0.06368475  0.2738385 ]]
6 1.4755614 [[-0.6006703  -1.192438   -2.0335174 ]
 [-0.7923758  -0.12075867 -0.257965  ]
 [ 0.47700804  0.10965797  0.2549411 ]]
7 1.4498222 [[-0.61477447 -1.1969451  -2.0149062 ]
 [-0.76682657 -0.15422934 -0.25004354]
 